---

- hosts: all
  #remote_user: root
  #gather_facts: no
  #become: yes
  #become_method: sudo

  vars:
    username: root

  tasks:

    - name: get user info
      getent:
        split: ":"
        database: passwd
        key: "{{ username }}"

    - name: Get authorized_keys
#      shell: cat "{{ getent_passwd[username][4]  }}"/.ssh/authorized_keys | cut -d' ' -f 1,3 >> check_keys.txt
      shell: cat "{{ getent_passwd[username][4]  }}"/.ssh/authorized_keys | cut -d' ' -f 1,3
      register: read_key

    - name: Get hostname
#      shell: echo $HOSTNAME
      shell: hostname
      register: result

    - name: append the output to a local file
      lineinfile:
#        dest: "output.txt"
        path: ~/output.txt
        create: true
        line: "\n{{ ansible_date_time.iso8601 }} - {{ result.stdout }} ( {{ ansible_default_ipv4.address|default(ansible_all_ipv4_addresses[0]) }} ): \n--------------------------------------\n{{ read_key.stdout }}"
        insertafter: EOF
      delegate_to: localhost

#    - name: Prints out hostname
#      debug: var=result.stdout

#    - name: Print out authorized_key
#      debug: var=read_key.stdout_lines
